### ISSUE TITLE
Default frame URL returns 404

### ISSUE THREAD

**Issue by brenes** [davidtranjs/3rd-cookie-check#1]
I guess that's because of the repo's url change buat the default URL https://dungmidside.github.io/3rd-cookie-check/checkpage.html is returning 404 error.

https://davidtranjs.github.io/3rd-cookie-check/readcookie.html is returning 200 so I guess this should be the default URL right?

**Comment by davidtranjs** [comment]
Yes, I will update it now, sorry for the change

**Comment by davidtranjs** [comment]
Hi @brenes I published new version `2.0.3` for fix this issue
Quick solution is 
```javascript
cookieCheck({ 
    iframeSrc: 'https://davidtranjs.github.io/3rd-cookie-check/readcookie.html' 
}).then(function(result) {
    const { supported, timeout } = result;
    // Your code here
})
```

**Comment by brenes** [comment]
Thanks a lot for the quick response! Awesome!

**Comment by brenes** [comment]
Just one comment, the right URL is the checkpage.html, right?

Am I mistaken or the quick solution should be like this?

```javascript
cookieCheck({ 
    iframeSrc: 'https://davidtranjs.github.io/3rd-cookie-check/readcookie.html' 
}).then(function(result) {
    const { supported, timeout } = result;
    // Your code here
})
```

Thanks again!

**Comment by davidtranjs** [comment]
@brenes yes, you right
I should be `iframeSrc: 'https://davidtranjs.github.io/3rd-cookie-check/checkpage.html' `
